/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#004526",
        "primary-container": "#1b5e3a",
        "on-primary": "#ffffff",
        "on-primary-container": "#92d5a8",
        "secondary": "#895100",
        "secondary-container": "#fdaa48",
        "tertiary": "#003f65",
        "tertiary-container": "#005789",
        "canvas-bg": "#F7F5F0",
        "surface-card": "#FFFFFF",
        "surface-container": "#e1f2e7",
        "surface-container-low": "#e6f8ec",
        "surface-container-high": "#dbece1",
        "surface-container-highest": "#d5e7db",
        "surface-container-lowest": "#ffffff",
        "text-primary": "#1F2A24",
        "text-secondary": "#5B6B62",
        "border-structural": "#E0DED5",
        "status-success": "#2E7D32",
        "status-warning": "#ED8936",
        "status-error": "#C0392B",
        "status-info": "#1B6FA8",
        // Dark mode palette
        "dark-canvas-bg": "#12181A",
        "dark-surface-card": "#1B2224",
        "dark-primary": "#5FBE8A",
        "dark-secondary": "#E0A94D",
        "dark-text-primary": "#EDEFEC",
        "dark-text-secondary": "#A9B3AC",
        "dark-border-structural": "#2D3A34",
      },
      spacing: {
        "sidebar-width": "16rem",
        "topbar-height": "4rem",
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-base": "1rem",
        "space-lg": "1.25rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "space-3xl": "2.5rem",
        "space-4xl": "3rem",
      },
      fontFamily: {
        heading: ["Poppins", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
}
